### ISSUE TITLE
Reproduce dataset

### ISSUE THREAD

**Issue by chontipan** [Ringbo/Cache#1]
Hi authors, your work is interesting. I am newbie in this field and I am recreating the method dataset. 

Could you please guide me how to generate the correct part of the large dataset? Can your provided script generate the correct samples?

Thank you.

**Comment by Ringbo** [comment]
Hi. Thank you for your interest. 
The correct part of large dataset is from the  [official link](https://zenodo.org/record/3653444#.YzwsTDRByUk) of ManySStuBs4J. Since the large set was prepared 2 years ago, I may not be able to find the original script for a short time. But this dataset is in json format so you can get the patches from the "fixPatch" key easily. If you mean the original buggy and fixed java file, you can retrieve them by crawling the link in https://github.com/(ownerName)/(projectName)/blob/[fixCommitParentSHA1/fixCommitSHA1]/[bugFilePath] format. Here is an example from ManySStuBs4J. Note that the "projectName" is in (ownerName).(projectName) format. Other items can be retrieved by parsing this json directly.
```json
{
  "bugType": "CHANGE_CALLER_IN_FUNCTION_CALL",
  "fixCommitSHA1": "796f45d14550420d66e1ed28daefeb45874d195f",
  "fixCommitParentSHA1": "9d35cf00d8e3a28f8bacb48a9a16aeceb974325d",
  "bugFilePath": "acra-limiter/src/main/java/org/acra/config/LimiterData.java",
  "fixPatch": "diff --git a/acra-limiter/src/main/java/org/acra/config/LimiterData.java b/acra-limiter/src/main/java/org/acra/config/LimiterData.java\nindex ce87635..6aad622 100644\n--- a/acra-limiter/src/main/java/org/acra/config/LimiterData.java\n+++ b/acra-limiter/src/main/java/org/acra/config/LimiterData.java\n@@ -80,7 +80,7 @@\n             put(KEY_STACK_TRACE, stacktrace);\n             final int index = stacktrace.indexOf('\\n');\n             final String firstLine = index == -1 ? stacktrace : stacktrace.substring(0, index);\n-            final int index2 = stacktrace.indexOf(':');\n+            final int index2 = firstLine.indexOf(':');\n             final String className = index2 == -1 ? firstLine : firstLine.substring(0, index2);\n             try {\n                 Class.forName(className);\n",
  "projectName": "ACRA.acra",
  "bugLineNum": 83,
  "bugNodeStartChar": 2722,
  "bugNodeLength": 23,
  "fixLineNum": 83,
  "fixNodeStartChar": 2722,
  "fixNodeLength": 22,
  "sourceBeforeFix": "stacktrace.indexOf(':')",
  "sourceAfterFix": "firstLine.indexOf(':')"
 }
```

Best,
Bo.

**Comment by chontipan** [comment]
Thank you for your reply and your guide.
